services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: establecimientos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuarios
    ports:
      - "5433:5433"
    volumes:
      - user-db_data:/var/lib/postgresql/data
      - ./initUser.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: auth-service

    depends_on:
      - user-db

  frontend_auth:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: frontend_auth

volumes:
  db_data:
  user-db_data: