services:
  db:
    build:
      context: ./db-establecimientos
      dockerfile: Dockerfile
    container_name: db
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: establecimientos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user-db:
    build:
      context: ./db-user
      dockerfile: Dockerfile
    container_name: user-db
    environment:
      POSTGRES_USER: monos
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuarios
    ports:
      - "5433:5433"
    volumes:
      - user-db_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: auth-service

    depends_on:
      - user-db
      
volumes:
  db_data:
  user-db_data: