name: Build and Deploy db-user to Azure

on:
  push:
    branches: [main]
    paths:
      - 'db-user/**'
  workflow_dispatch:

env:
  IMAGE_NAME: user-db
  RESOURCE_GROUP: monosGPS
  CONTAINER_APP: user-db-app
  ACR_SERVER: monosgps.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ env.ACR_SERVER }}

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: ./db-user
          file: ./db-user/Dockerfile
          push: true
          tags: ${{ env.ACR_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Ensure Azure CLI is ready
        run: |
          az extension add --name containerapp --yes
          az provider register --namespace Microsoft.App
          az provider register --namespace Microsoft.OperationalInsights

      - name: Deploy to Azure Container App
        run: |
          az containerapp show --name $CONTAINER_APP --resource-group $RESOURCE_GROUP || \
          az containerapp create \
            --name $CONTAINER_APP \
            --resource-group $RESOURCE_GROUP \
            --environment $CONTAINER_ENV \
            --image $ACR_SERVER/$IMAGE_NAME:latest \
            --target-port 8080 \
            --ingress external \
            --registry-server $ACR_SERVER \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}

          az containerapp update \
            --name $CONTAINER_APP \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_SERVER/$IMAGE_NAME:latest

