name: CI with Docker Compose

on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and run containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 15

      - name: Check containers are running
        run: docker ps

      # Opcional: ejecutar pruebas (ajústalo a tu tecnología)
      # Ejemplo para una app Java con Maven
      # - name: Run tests
      #   run: docker exec auth-service mvn test

      - name: Shut down containers
        run: docker-compose down
