name: Build and Push Frontend

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker image tag with SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: fyjo/monosgps-frontend:${{ env.IMAGE_TAG }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ChristianDDiazR/monosGPS_Deploy
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-repo

      - name: Update deployment image tag
        run: |
          FILE_PATH="gitops-repo/k8s/frontend/deployment.yaml"
          sed -i "s|\(image: fyjo/monosgps-frontend:\).*|\1${{ env.IMAGE_TAG }}|" "$FILE_PATH"

      - name: Commit and push changes
        run: |
          cd gitops-repo
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Update authservice image tag to ${{ env.IMAGE_TAG }}"
          git push

