name: Build and Push AuthService

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'AuthService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Puedes especificar la versión de Java que necesitas
        distribution: 'temurin'  # Usando la distribución Temurin

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run tests
      run: mvn test
