name: Build and Push AuthService

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'AuthService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Asegúrate de usar la versión correcta de Java
        distribution: 'adoptium'  # Usando Adoptium en lugar de adoptopenjdk

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run tests
      run: mvn test
