name: Build and Push testing

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'AuthService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      working-directory: AuthService

    - name: Run tests
      run: mvn test
      working-directory: AuthService
